input_directory: "./data/ptb-xl/"
header_directory: "./data/ptb-xl/"
output_directory: "./data/generated_images/"

# start and end indices of ECG records
start_index: 1
end_index: 5

# image parameters
wrinkles: true # overlay wrinkles on the ECG images
resolution: 200
bernoulli_dc: 0.5 # probability of adding the 1 mV control signal

random_values:
  line_width_min: 0.5 # signal width
  line_width_max: 2.0
  grid_line_width_min: 0.9 # grid width
  grid_line_width_max: 1.6
  lead_fontsize_min: 0.7 # font size for denoting leads, for example, I, II, III, etc.
  lead_fontsize_max: 2.0
  lead_name_offset_min: -1.0 # vertical offset for lead names
  lead_name_offset_max: 2.0
  major_red_min: 0.6 # color of the major grid lines
  major_red_max: 1.0
  major_green_min: 0.4
  major_green_max: 0.7
  major_blue_min: 0.4
  major_blue_max: 0.7
  minor_offset_min: 0.1 # how much brighter the minor grid lines are compared to the major grid lines
  minor_offset_max: 0.3
  grey_min: 0.0 # color of the ECG signal
  grey_max: 0.3